### PR TITLE
Dashboard

### PR DESCRIPTION
**Pull request by skelterjohn**

### CODE REVIEW

**Comment by mirtchovski** [comment]
Is this merging the dashboard branch into master?

**Comment by skelterjohn** [comment]
yes

**Comment by mirtchovski** [comment]
are you expecting to make changes to dashboard/*? I have uncommitted
changes there and am waiting for brian/erik to comment on a few things.

**Comment by skelterjohn** [comment]
I do not expect to touch dashboard. I wanted the instance monitor stuff.

If you want comments, you should make a pull request!

**Comment by mirtchovski** [comment]
not comments, more questions:
- log.Fatal, skynet.log.Panic or os.Exit? all three seem to be used, should
  I convert to skynet.Log.Panic instead?
- panic across library boundary, ok? (doozer.go has 7 recovers alone,
  dashboard 1)
- environment variables: prepended with SKYNET or not? SKYNET_MGOSERVER or
  just MGOSERVER (or is there an equivalent?)
- non-gofmt-ed code: should gofmt, or should switch to 2-space tabs?

one comment on instancesocket.go: you can use websocket.JSON.Send and
websocket.JSON.Receive for less code.

if the pull requests are the preferred way to go then I'll stick with them.

**Comment by bketelsen** [comment]
I think skynet.Log.Panic is best
I think we should contain panics to libraries like Go conventions do
I like the SKYNET prefix for env vars, but it makes them big.  Does anyone care if they're long?
let's gofmt everything every time.

**Pull request merged**
