### PR TITLE
New API works for rand-init/-agent

### PR DESCRIPTION
**Pull request by cdunn2001**
However, none of the other Agents have been modified yet, in order
to reduce the number of diffs to examine. Thus, there is some
duplicate code in skylib. We will address that soon...

### CODE REVIEW

**Comment by bketelsen** [comment]
this looks pretty good.  If I pull this now and start working on Redis will that be in your way while you finish the cleanup?

**Comment by cdunn2001** [comment]
I already have the filesystem version of the Doozer API ready. Once this is pulled, I'll submit that next step. (That's why the doozer-specific stuff is pulled into `doozer.go`.)

For now, it is the Doozer API precisely, but we can change that. The earlier we agree on the API, the better. Then you can do the Redis stuff without affecting anything else.

**Comment by bketelsen** [comment]
Pulled.

**Comment by bketelsen** [comment]
come to think of it, MongoDB would be dead simple for a storage engine.  I need to see if mongo supports watches.  If not, we could do a 1s poll.

**Pull request merged**
