### PR TITLE
mango initiator example

### PR DESCRIPTION
**Pull request by paulbellamy**
I added a quick mango initiator example.  It's basically quick copy/paste hack-job of the other one.  Figured it was the least I could do to contribute. :)

### CODE REVIEW

**Comment by cdunn2001** [comment]
This has the same problem as another example: myStartup is missing. But bk and I will address that ourselves.

Thanks, Paul!

**Comment by paulbellamy** [comment]
Odd. Both of them compiled fine here...
(release golang)

**Comment by cdunn2001** [comment]
Interesting. Are you using **gb**?

**Comment by cdunn2001** [comment]
If you have any ideas, you can post here: https://github.com/bketelsen/skynet/issues/19

**Comment by paulbellamy** [comment]
yeah, I was using gb

**Comment by bketelsen** [comment]
I take one day off to write the web development chapter in my book and you guys kick up a storm around here.  Nice.

**Pull request merged**
