### PR TITLE
Fixed merge conflicts

### PR DESCRIPTION
**Pull request by elimisteve**
Pulling should be trivial now.

### CODE REVIEW

**Comment by erikstmartin** [comment]
LGTM aside from the Ambiguous name of Payload, the need for helpers to create these payloads in case you don't want to supply any additional criteria you don't need to create the object before each message, and we might want to log errors for logging straight to stdout from within the logging API so that each call to log doesn't have to account for the error

**Comment by erikstmartin** [comment]
also i notice that the payloads are created using &Payload{} so we are creating pointers to these messages, this could possibly end up creating these on the heap, and creating more garbage for the GC to cleanup.

I know Go's gc has some smart logic about whether or not to create on the heap vs stack if the pointers are passed to other functions/returning, but probably safer that sorry as there isn't really a need for these to be pointers, at least from what i can tell.

**Comment by elimisteve** [comment]
I almost always use pointers when I can so that data structures aren't unnecessarily copied multiple times as they're passed around.

If you find some docs, comments, or the like that suggest my approach is less efficient rather than more efficient, let me know. I am also not sure what exactly confuses/causes problems for the GC.

**Comment by elimisteve** [comment]
Yay!

**Pull request merged**
