### PR TITLE
Allow skydaemon to take an optional flag for which mongodb server to connect to

### PR DESCRIPTION
**Pull request by lfranchi**
This is my first pull request so feel free to let me know what I've done wrong :) I tried to keep the code duplication down by splitting GetServiceConfigFromFlags into two.

I was having issues with the default Vagrantfile setup with all the non-main VMs trying to connect to a mongo on localhost that was hardcoded---the mongo server is only running on one of the 5 vms.

cheers,
leo

### CODE REVIEW

**Comment by skelterjohn** [comment]
This seems fine, on its own, but it might be worth it to add some kind of standardized method for setting the mongo host. Many services will want to do this.

**Comment by erikstmartin** [comment]
Agreed, now that mongo logging has been updated by Steve, we need to have a shared way to get the value for all clients/services, that's reusable. We might want to move this into one of the helper methods inside config.go GetServiceConfigFromFlags/GetClientConfigFromFlags

**Comment by lfranchi** [comment]
Makes sense. Is mongo logging used only by services, or only by clients, or both? I can move the mongo flags into the appropriate Get*ConfigFromFlags

**Comment by erikstmartin** [comment]
It will be used by both, if the implementors choose to use it, it's possible for any given service/client that they may just want to log to console etc.

**Comment by lfranchi** [comment]
Ok, cool. I moved the code to be shared and any client/server can access the mongo host/db if they so desire.

**Comment by erikstmartin** [comment]
Awesome, thanks for the contribution, do you want to add yourself to the documentation/contributors.txt file as part of this pull-request and i'll go ahead and get it merged in and tested.

**Comment by lfranchi** [comment]
Sure, though this a bit of a trivial change :) Updated. Thanks for the reviews!

**Comment by bketelsen** [comment]
Thanks for the contribution!

**Pull request merged**
