### PR TITLE
Dashboard: better error messages for logger

### PR DESCRIPTION
**Pull request by mirtchovski**
switched from Println to Printf; now messages carry the remote address of the requestee.

### CODE REVIEW

**Comment by skelterjohn** [comment]
You shouldn't use .Println or .Printf for logging. A raw string is not convenient to search for in a database. Instead use log.Item() with a custom type. See skynet/logmessages.go. You only have to make a .String() method for pretty printing on the console. It will go into mongo as a serialized json object, paired with the program's UUID and the type of the message.

**Comment by mirtchovski** [comment]
moved the discussion in chat.

**Comment by mirtchovski** [comment]
PTAL

**Comment by skelterjohn** [comment]
LGTM

**Pull request merged**
